/*=================================================================================*/
/*  File        : GPIO_CONFIG_H                                                  */
/*  Description : This Program file includes AFIO program for STM32f103C8T6        */
/*  Abdelrahman Ellithy
 *  layer: MCAL
 *  SW component: GPIO
 *  																				*/
#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

#include "MCAL/GPIO/GPIO_interface.h"

#define PORTA_EN		1
#define PORTB_EN		1
#define PORTC_EN		0
#define NeedPortHere 	1


#define INPUT_FLOATING 0
#define OUTPUT_LOW     0
#define OUTPUT_HIGH    1
/*
	$ Options :-

		GPIO_INPUT_ANALOG
		GPIO_INPUT_FLOATING
		GPIO_INPUT_PULL_DOWN
		GPIO_INPUT_PULL_UP

		***********************
		***********************
		GPIO_OUTPUT_GP_PP_10MHZ
		GPIO_OUTPUT_GP_OD_10MHZ
		GPIO_OUTPUT_AF_PP_10MHZ
		GPIO_OUTPUT_AF_OD_10MHZ

		GPIO_OUTPUT_GP_PP_2MHZ
		GPIO_OUTPUT_GP_OD_2MHZ
		GPIO_OUTPUT_AF_PP_2MHZ
		GPIO_OUTPUT_AF_OD_2MHZ

		GPIO_OUTPUT_GP_PP_50MHZ
		GPIO_OUTPUT_GP_OD_50MHZ
		GPIO_OUTPUT_AF_PP_50MHZ
		GPIO_OUTPUT_AF_OD_50MHZ

*/
#if NeedPortHere==1
u8 PORTA_DIR[]={
/*PORTA_PIN0_DIR	*/	 GPIO_INPUT_ANALOG
/*PORTA_PIN1_DIR	*/	,GPIO_INPUT_ANALOG
/*PORTA_PIN2_DIR	*/	,GPIO_OUTPUT_AF_OD_10MHZ
/*PORTA_PIN3_DIR	*/	,GPIO_INPUT_FLOATING
/*PORTA_PIN4_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN5_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN6_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN7_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN8_DIR	*/	,GPIO_OUTPUT_AF_PP_2MHZ
/*PORTA_PIN9_DIR	*/	,GPIO_OUTPUT_AF_PP_2MHZ
/*PORTA_PIN10_DIR	*/	,GPIO_OUTPUT_AF_PP_2MHZ
/*PORTA_PIN11_DIR	*/	,GPIO_OUTPUT_AF_PP_2MHZ
/*PORTA_PIN12_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN13_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN14_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTA_PIN15_DIR	*/	,GPIO_OUTPUT_GP_PP_2MHZ

};
u8 PORTB_DIR[]={
/*PORTB_PIN0_DIR	*/		 GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN1_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN2_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN3_DIR	*/		,GPIO_INPUT_PULL_UP
/*PORTB_PIN4_DIR	*/		,GPIO_INPUT_PULL_UP
/*PORTB_PIN5_DIR	*/		,GPIO_INPUT_PULL_UP
/*PORTB_PIN6_DIR	*/		,GPIO_INPUT_PULL_UP
/*PORTB_PIN7_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN8_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN9_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN10_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN11_DIR	*/		,GPIO_INPUT_FLOATING
/*PORTB_PIN12_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN13_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN14_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ
/*PORTB_PIN15_DIR	*/		,GPIO_OUTPUT_GP_PP_2MHZ

};
u8 PORTC_DIR[]={
/*PORTC_PIN13_DIR*/		 GPIO_INPUT_PULL_UP
/*PORTC_PIN14_DIR*/		,GPIO_INPUT_PULL_UP
/*PORTC_PIN15_DIR*/		,GPIO_INPUT_PULL_UP

};


/******	set initial values for the pins	******************
 * *******************************************************
 * *******************************************************/
/*  $ Choose:-
			1- INPUT_FLOATING
			3- OUTPUT_LOW
			4- OUTPUT_HIGH
*/
u8 PORTA_init_val[]={
/*PORTA_PIN0_INITIAL_VALUE  */	 INPUT_FLOATING
/*PORTA_PIN1_INITIAL_VALUE  */	,INPUT_FLOATING
/*PORTA_PIN2_INITIAL_VALUE  */	,INPUT_FLOATING
/*PORTA_PIN3_INITIAL_VALUE  */	,OUTPUT_HIGH
/*PORTA_PIN4_INITIAL_VALUE  */	,OUTPUT_HIGH
/*PORTA_PIN5_INITIAL_VALUE  */	,OUTPUT_HIGH
/*PORTA_PIN6_INITIAL_VALUE  */	,OUTPUT_HIGH
/*PORTA_PIN7_INITIAL_VALUE  */	,OUTPUT_LOW
/*PORTA_PIN8_INITIAL_VALUE  */	,OUTPUT_LOW
/*PORTA_PIN9_INITIAL_VALUE  */	,OUTPUT_LOW
/*PORTA_PIN10_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTA_PIN11_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTA_PIN12_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTA_PIN13_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTA_PIN14_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTA_PIN15_INITIAL_VALUE	*/	,OUTPUT_HIGH

};
u8 PORTB_init_val[]={
/*PORTB_PIN0_INITIAL_VALUE	*/	 OUTPUT_LOW
/*PORTB_PIN1_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN2_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN3_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN4_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN5_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN6_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN7_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN8_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN9_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN10_INITIAL_VALUE	*/	,OUTPUT_LOW
/*PORTB_PIN11_INITIAL_VALUE	*/	,INPUT_FLOATING
/*PORTB_PIN12_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN13_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN14_INITIAL_VALUE	*/	,OUTPUT_HIGH
/*PORTB_PIN15_INITIAL_VALUE	*/	,OUTPUT_HIGH
};
u8 PORTC_init_val[]={
/*PORTC_PIN13_INITIAL_VALUE*/		 INPUT_FLOATING
/*PORTC_PIN14_INITIAL_VALUE*/		,INPUT_FLOATING
/*PORTC_PIN15_INITIAL_VALUE*/		,INPUT_FLOATING
};
#endif
#endif
